package org.tmforum.mtnm.flowDomain;

/**
 *	Generated from IDL interface "FlowDomainMgr_I"
 *	@author JacORB IDL compiler V 2.2.3, 10-Dec-2005
 */


public interface FlowDomainMgr_IOperations
	extends org.tmforum.mtnm.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllFlowDomains(int how_many, org.tmforum.mtnm.flowDomain.FDList_THolder flowDomains, org.tmforum.mtnm.flowDomain.FDIterator_IHolder fdIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getFlowDomainsByUserLabel(java.lang.String userLabel, org.tmforum.mtnm.flowDomain.FDList_THolder flowDomains) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.flowDomain.FlowDomain_THolder flowDomain) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAssociatingFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, org.tmforum.mtnm.flowDomain.FlowDomain_THolder flowDomain) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getTransmissionParams(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] name, java.lang.String[] filter, org.tmforum.mtnm.transmissionParameters.LayeredParameterList_THolder transmissionParams) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createFlowDomain(org.tmforum.mtnm.flowDomain.FDCreateData_T createData, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder assignedCPTPs, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.flowDomain.FlowDomain_THolder theFD, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deleteFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.flowDomain.FDModifyData_T fdModifyData, org.tmforum.mtnm.flowDomain.FlowDomain_THolder modifiedFD, org.omg.CORBA.StringHolder failedAttributes, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void associateMFDsWithFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] mfdNames, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deAssociateMFDsFromFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] mfdNames, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void associateCPTPsWithFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] cptpNames, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deAssociateCPTPsFromFlowDomain(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] tpNames, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllAssociatedMFDs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tmdOrFdName, int how_many, org.tmforum.mtnm.flowDomain.MFDList_THolder mfds, org.tmforum.mtnm.flowDomain.MFDIterator_IHolder mfdIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSupportedMFDs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] holderName, int how_many, org.tmforum.mtnm.flowDomain.MFDList_THolder mfds, org.tmforum.mtnm.flowDomain.MFDIterator_IHolder mfdIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getMFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, org.tmforum.mtnm.flowDomain.MatrixFlowDomain_THolder mfd) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAssigningMFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] cptpName, org.tmforum.mtnm.flowDomain.MatrixFlowDomain_THolder mfd) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createMFD(org.tmforum.mtnm.flowDomain.MFDCreateData_T createData, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.flowDomain.MatrixFlowDomain_THolder theMFD, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deleteMFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyMFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, org.tmforum.mtnm.flowDomain.MFDModifyData_T mfdModifyData, org.tmforum.mtnm.flowDomain.MatrixFlowDomain_THolder newMFD, org.omg.CORBA.StringHolder failedAttributes, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void assignCPTPsToMFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] tpNames, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void unassignCPTPsFromMFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] tpNames, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createFTP(org.tmforum.mtnm.flowDomain.FTPCreateData_T createData, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.terminationPoint.TerminationPoint_THolder theFTP, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deleteFTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] ftpName, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCPTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, org.tmforum.mtnm.flowDomain.CPTP_Role_T cptpRole, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder cptpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllAssignedCPTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder cptpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllAssignableCPTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mfdName, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder cptpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFDFrs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectivityRateList, org.tmforum.mtnm.flowDomainFragment.FDFrList_THolder fdfrList, org.tmforum.mtnm.flowDomainFragment.FDFrIterator_IHolder fdfrIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getFDFrsWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] cptpName, int how_many, org.tmforum.mtnm.flowDomainFragment.FDFrList_THolder fdfrList, org.tmforum.mtnm.flowDomainFragment.FDFrIterator_IHolder fdfrIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getFDFrsByUserLabel(java.lang.String userLabel, org.tmforum.mtnm.flowDomainFragment.FDFrList_THolder fdfrs) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getFDFr(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdfrName, org.tmforum.mtnm.flowDomainFragment.FlowDomainFragment_THolder fdfr) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createAndActivateFDFr(org.tmforum.mtnm.flowDomainFragment.FDFrCreateData_T createData, org.tmforum.mtnm.flowDomain.ConnectivityRequirement_T connectivityRequirement, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] aEnd, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] zEnd, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder internalTPs, org.tmforum.mtnm.flowDomainFragment.MatrixFlowDomainFragmentList_THolder mfdfrs, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.flowDomainFragment.FlowDomainFragment_THolder theFDFr, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deactivateAndDeleteFDFr(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdfrName, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.flowDomainFragment.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyFDFr(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdfrName, org.tmforum.mtnm.flowDomainFragment.FDFrModifyData_T fdfrModifyData, org.tmforum.mtnm.flowDomain.ConnectivityRequirement_T connectivityRequirement, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder failedTPList, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.tmforum.mtnm.flowDomainFragment.FlowDomainFragment_THolder newFDFr, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinksOfFD(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] flowDomainName, int how_many, org.tmforum.mtnm.topologicalLink.TopologicalLinkList_THolder topoList, org.tmforum.mtnm.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getFDFrRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] fdfrName, org.tmforum.mtnm.flowDomainFragment.FDFrRoute_THolder route) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
}
