package org.tmforum.mtnm.managedElementManager;

/**
 *	Generated from IDL interface "ManagedElementMgr_I"
 *	@author JacORB IDL compiler V 2.2.3, 10-Dec-2005
 */


public interface ManagedElementMgr_IOperations
	extends org.tmforum.mtnm.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllManagedElements(int how_many, org.tmforum.mtnm.managedElement.ManagedElementList_THolder meList, org.tmforum.mtnm.managedElement.ManagedElementIterator_IHolder meIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllManagedElementNames(int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainingSubnetworkNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder subnetNames) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllPTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllPTPsWithoutFTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllPTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllPTPNamesWithoutFTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, org.tmforum.mtnm.terminationPoint.TerminationPoint_THolder tp) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getManagedElement(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, org.tmforum.mtnm.managedElement.ManagedElement_THolder me) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainedPotentialTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] layerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainedPotentialTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] layerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainedInUseTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] layerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainedInUseTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] layerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainedCurrentTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] layerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainedCurrentTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] layerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainingTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainingTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder tpNameList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllActiveAlarms(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] meName, java.lang.String[] excludeProbCauseList, org.tmforum.mtnm.notifications.PerceivedSeverity_T[] excludeSeverityList, int how_many, org.tmforum.mtnm.notifications.EventList_THolder eventList, org.tmforum.mtnm.notifications.EventIterator_IHolder eventIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllUnacknowledgedActiveAlarms(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] meName, java.lang.String[] excludeProbCauseList, org.tmforum.mtnm.notifications.PerceivedSeverity_T[] excludeSeverityList, int how_many, org.tmforum.mtnm.notifications.EventList_THolder eventList, org.tmforum.mtnm.notifications.EventIterator_IHolder eventIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void setTPData(org.tmforum.mtnm.subnetworkConnection.TPData_T tpInfo, org.tmforum.mtnm.terminationPoint.TerminationPoint_THolder modifiedTP) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCrossConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.tmforum.mtnm.subnetworkConnection.CrossConnectList_THolder ccList, org.tmforum.mtnm.subnetworkConnection.CCIterator_IHolder ccIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createGTP(java.lang.String userLabel, boolean forceUniqueness, java.lang.String owner, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] listOfTPs, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] initialCTPname, int numberOfCTPs, org.tmforum.mtnm.terminationPoint.GTPEffort_T gtpEffort, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] additionalCreationInfo, org.tmforum.mtnm.terminationPoint.GTP_THolder newGTP) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deleteGTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] gtpName) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyGTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] gtpName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] tpNames, java.lang.String actionType, org.tmforum.mtnm.terminationPoint.GTP_THolder modifiedGTP) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getGTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] gtpName, org.tmforum.mtnm.terminationPoint.GTP_THolder gtp) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllGTPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, int how_many, org.tmforum.mtnm.terminationPoint.GTPlist_THolder gtpList, org.tmforum.mtnm.terminationPoint.GTPiterator_IHolder gtpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllGTPNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] tpLayerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getContainingGTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] ctpName, org.tmforum.mtnm.terminationPoint.GTP_THolder gtp) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void setGtpAlarmReportingOn(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] gtpName) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void setGtpAlarmReportingOff(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] gtpName) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void verifyTMDAssignment(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, org.tmforum.mtnm.terminationPoint.Directionality_T direction, org.omg.CORBA.StringHolder tmdAssignmentState, org.tmforum.mtnm.transmissionParameters.LayeredParameterList_THolder transmissionParams, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalTPInfo) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFixedCrossConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.tmforum.mtnm.subnetworkConnection.CrossConnectList_THolder ccList, org.tmforum.mtnm.subnetworkConnection.CCIterator_IHolder ccIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getPotentialFixedCCs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] inputTP, org.tmforum.mtnm.globaldefs.NVSList_THolder ContainingTP, org.tmforum.mtnm.globaldefs.NVSList_THolder potentialCCList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
}
