package org.tmforum.mtnm.multiLayerSubnetwork;

/**
 *	Generated from IDL interface "MultiLayerSubnetworkMgr_I"
 *	@author JacORB IDL compiler V 2.2.3, 10-Dec-2005
 */


public interface MultiLayerSubnetworkMgr_IOperations
	extends org.tmforum.mtnm.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllManagedElements(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.managedElement.ManagedElementList_THolder meList, org.tmforum.mtnm.managedElement.ManagedElementIterator_IHolder meIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllManagedElementNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getMultiLayerSubnetwork(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, org.tmforum.mtnm.multiLayerSubnetwork.MultiLayerSubnetwork_THolder subnetwork) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinks(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.topologicalLink.TopologicalLinkList_THolder topoList, org.tmforum.mtnm.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinkNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getTopologicalLink(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] topoLinkName, org.tmforum.mtnm.topologicalLink.TopologicalLink_THolder topoLink) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllEdgePoints(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllEdgePointNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, short[] layerRateList, short[] connectionLayerRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAssociatedTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getTPGroupingRelationships(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.tmforum.mtnm.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionsWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.tmforum.mtnm.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionNamesWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, boolean includeHigherOrderCCs, org.tmforum.mtnm.subnetworkConnection.Route_THolder route) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getRouteAndTopologicalLinks(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.Route_THolder route, org.tmforum.mtnm.topologicalLink.TopologicalLinkList_THolder topologicalLinkList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder snc) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getSNCsByUserLabel(java.lang.String userLabel, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createSNC(org.tmforum.mtnm.subnetworkConnection.SNCCreateData_T createData, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void activateSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createAndActivateSNC(org.tmforum.mtnm.subnetworkConnection.SNCCreateData_T createData, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deactivateSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deleteSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deactivateAndDeleteSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void checkValidSNC(org.tmforum.mtnm.subnetworkConnection.SNCCreateData_T createData, org.tmforum.mtnm.subnetworkConnection.TPData_T[] tpsToModify, boolean considerResources, org.omg.CORBA.BooleanHolder valid) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllTPPools(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetworkName, int how_many, org.tmforum.mtnm.terminationPoint.TerminationPointList_THolder tpList, org.tmforum.mtnm.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllTPPoolNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetworkName, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFixedSubnetworkConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.tmforum.mtnm.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFixedSubnetworkConnectionNames(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFixedSubnetworkConnectionsWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.tmforum.mtnm.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllFixedSubnetworkConnectionNamesWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, org.tmforum.mtnm.globaldefs.NamingAttributesList_THolder nameList, org.tmforum.mtnm.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createModifiedSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.tmforum.mtnm.subnetworkConnection.SNCModifyData_T SNCModifyData, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.subnetworkConnection.ProtectionEffort_T tolerableImpactEffort, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder newSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void swapSNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] nameOfSNCtoBeDeactivated, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] nameOfSNCtoBeActivated, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SNCState_THolder stateOfActivatedSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifySNC(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.tmforum.mtnm.subnetworkConnection.SNCModifyData_T SNCModifyData, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.subnetworkConnection.ProtectionEffort_T tolerableImpactEffort, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnection_THolder newSNC, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getBackupRoutes(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, boolean includeHigherOrderCCs, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalInfo, org.tmforum.mtnm.subnetworkConnection.RouteList_THolder routeList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void switchRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalInfo, org.tmforum.mtnm.subnetworkConnection.SNCState_THolder sncState, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void addRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.RouteCreateData_T createRoute, org.tmforum.mtnm.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.subnetworkConnection.RouteDescriptor_THolder theRoute, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void removeRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.tmforum.mtnm.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalInfo) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void setIntendedRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalInfo) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void setRoutesAdminState(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, org.tmforum.mtnm.subnetworkConnection.RouteNameAndAdminStateList_THolder routeNameAndAdminStateList, org.tmforum.mtnm.subnetworkConnection.SNCState_THolder sncState) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getIntendedRoute(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] sncName, boolean includeHigherOrderCCs, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalInfo, org.tmforum.mtnm.subnetworkConnection.Route_THolder route) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void createTPPool(org.tmforum.mtnm.multiLayerSubnetwork.TPPoolCreateData_T newTPPoolCreateData, org.tmforum.mtnm.terminationPoint.TerminationPoint_THolder newTPPool) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void deleteTPPool(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tpPoolName) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyTPPool(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tPPoolName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] containedMembers, java.lang.String actionType, org.tmforum.mtnm.terminationPoint.TerminationPoint_THolder modifiedTPPool) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getTPPool(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tPPoolName, org.tmforum.mtnm.terminationPoint.TerminationPoint_THolder tPPool, org.omg.CORBA.IntHolder numberOfMembers, org.omg.CORBA.IntHolder numberOfIdleMembers, org.omg.CORBA.StringHolder descriptionOfUse) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSubordinateMLSNs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.multiLayerSubnetwork.SubnetworkList_THolder subordinateMLSNsList, org.tmforum.mtnm.multiLayerSubnetwork.SubnetworkIterator_IHolder subnetIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllSubordinateRAidsWithConnection(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] connection, java.lang.String routeType, org.tmforum.mtnm.multiLayerSubnetwork.RoutePerRouteType_THolder routePerRouteType) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getMLSNPPLink(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mLSNPPLinkName, boolean sNPListRequested, org.tmforum.mtnm.mLSNPPLink.MultiLayerSNPPLink_THolder theMLSNPPLink) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllMLSNPPLinks(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, boolean sNPListRequested, int how_many, org.tmforum.mtnm.mLSNPPLink.MLSNPPLinkList_THolder mLSNPPLinkList, org.tmforum.mtnm.mLSNPPLink.MLSNPPLinkIterator_IHolder mLSNPPLinkIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllInternalMLSNPPLinks(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, boolean sNPListRequested, int how_many, org.tmforum.mtnm.mLSNPPLink.MLSNPPLinkList_THolder mLSNPPLinkList, org.tmforum.mtnm.mLSNPPLink.MLSNPPLinkIterator_IHolder mLSNPPLinkIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllEdgeMLSNPPLinks(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, boolean sNPListRequested, int how_many, org.tmforum.mtnm.mLSNPPLink.MLSNPPLinkList_THolder mLSNPPLinkList, org.tmforum.mtnm.mLSNPPLink.MLSNPPLinkIterator_IHolder mLSNPPLinkIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllMLSNPPs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, boolean sNPListRequested, int how_many, org.tmforum.mtnm.mLSNPP.MLSNPPList_THolder mLSNPPList, org.tmforum.mtnm.mLSNPP.MLSNPPIterator_IHolder mLSNPPIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallsAndTopLevelConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsList_THolder callAndTopLevelConnectionsList, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsIterator_IHolder callAndTopLevelConnectionsIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallsAndTopLevelConnectionsAndSNCs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCsList_THolder callAndTopLevelConnectionsAndSNCsList, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCsIterator_IHolder callAndTopLevelConnectionsAndSNCsIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallsAndTopLevelConnectionsWithME(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] meName, int how_many, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsList_THolder callAndTopLevelConnectionsList, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsIterator_IHolder callAndTopLevelConnectionsIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallsAndTopLevelConnectionsAndSNCsWithME(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] meName, int how_many, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCsList_THolder callAndTopLevelConnectionsAndSNCsList, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCsIterator_IHolder callAndTopLevelConnectionsAndSNCsIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallsAndTopLevelConnectionsAndSNCsWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] subnetName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tPName, int how_many, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCsList_THolder callAndTopLevelConnectionsAndSNCsList, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCsIterator_IHolder callAndTopLevelConnectionsAndSNCsIt) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallIdsWithTP(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] tPName, org.tmforum.mtnm.callSNC.CallIdList_THolder callIdList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getAllCallIdsWithSNPPOrTNAName(org.tmforum.mtnm.globaldefs.NameAndStringValue_T sNPPOrTNAName, org.tmforum.mtnm.callSNC.CallIdList_THolder callIdList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getCallAndTopLevelConnectionsAndSNCs(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCs_THolder callAndTopLevelConnectionsAndSNCs) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getCallAndTopLevelConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, java.lang.String callId, org.tmforum.mtnm.callSNC.CallAndTopLevelConnections_THolder callAndTopLevelConnections) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void establishCall(org.tmforum.mtnm.callSNC.CallCreateData_T callCreateData, org.tmforum.mtnm.subnetworkConnection.SNCCreateData_T[] connectionCreateDataList, java.lang.String routeGroupsNumber, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.callSNC.CallAndTopLevelConnectionsAndSNCs_THolder callAndTopLevelConnectionsAndSNCs, org.tmforum.mtnm.subnetworkConnection.SNCCreateDataList_THolder sNCsNotCreated, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder partialSNCs, org.omg.CORBA.StringHolder callErrorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyCall(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.callSNC.CallModifyData_T callModifyData, org.tmforum.mtnm.callSNC.Call_THolder modifiedCall) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void releaseCall(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder remainingSNCs, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getCall(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.callSNC.Call_THolder theCall) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void addConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.subnetworkConnection.SNCCreateData_T[] connectionsToAdd, boolean connectionRouteReArrangementAllowed, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder connectionList, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder partialSNCs, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void removeConnections(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[][] connectionNamesList, org.tmforum.mtnm.subnetworkConnection.TPDataList_THolder tpsToModify, org.tmforum.mtnm.subnetworkConnection.SubnetworkConnectionList_THolder sNCsNotDeleted, org.omg.CORBA.StringHolder errorReason) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void getConnectionsAndRouteDetails(java.lang.String callID, org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] mLRAName, java.lang.String sNPOrSNPPID, boolean mLSNPPLinkRequested, java.lang.String routeType, org.tmforum.mtnm.callSNC.SNCAndRouteList_THolder connectionAndRouteList) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
	void modifyDiversityAndCorouting(org.tmforum.mtnm.globaldefs.NameAndStringValue_T[] callName, org.tmforum.mtnm.callSNC.Diversity_T callDiversity, org.tmforum.mtnm.callSNC.RouteGroupInfo_T[] routeGroupInfoList, boolean connectionRouteReArrangementAllowed, java.lang.String routeGroupsNumber, org.tmforum.mtnm.globaldefs.NVSList_THolder additionalInfo, org.tmforum.mtnm.callSNC.CallAndTopLevelConnections_THolder callAndTopLevelConnections) throws org.tmforum.mtnm.globaldefs.ProcessingFailureException;
}
